### PR TITLE
Meeting minutes for 16 Aug 2022 and 22 Aug 2022

### PR DESCRIPTION
**Pull request by ZichengQu**
Signed-off-by: ZichengQu <quzicheng315@gmail.com>

### CODE REVIEW

**Comment by li-clement** [comment]
Thanks all guys about the charter reviews.

**Comment by li-clement** [comment]
LGTM

**Review by lindayi — APPROVED** [review]
LGTM

**Review by li-clement — APPROVED** [review]
LGTM

**Pull request merged**
