### PR TITLE
Add technical charter to the project

### LINKED ISSUE #37: A sandbox project charter is needed
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A sandbox project charter is needed to define the TSC and its responsibility.

### PR DESCRIPTION
**Pull request by li-clement**
Signed-off-by: Clement Li <lizi4@huawei.com>   fix #37

### CODE REVIEW

**Comment by rgopikrishnan91** [comment]
I would suggest modifying the mission to "**Mission**. The mission of the Project is to provide a crowd-sourced platform that provides approaches to analyze and document the license compliance risks of publicly available datasets used for Artificial Intelligence (AI) software. In addition, the project endeavors to develop and promote open standards that capture the metadata required for performing license compliance analysis, dataset license compliance analysis processes and supporting tools."

**Comment by rgopikrishnan91** [comment]
Also for TSC members maybe in total lets have like 4-5 SIGs to begin with and group multiple TSC members being responsible for each group (maybe even Primary, secondary). Thoughts?

**Comment by li-clement** [comment]
> Also for TSC members maybe in total lets have like 4-5 SIGs to begin with and group multiple TSC members being responsible for each group (maybe even Primary, secondary). Thoughts?

That is what I think, all the TSC members need to be aware of the responsibility they have.

**Comment by li-clement** [comment]
> I would suggest modifying the mission to "**Mission**. The mission of the Project is to provide a crowd-sourced platform that provides approaches to analyze and document the license compliance risks of publicly available datasets used for Artificial Intelligence (AI) software. In addition, the project endeavors to develop and promote open standards that capture the metadata required for performing license compliance analysis, dataset license compliance analysis processes and supporting tools."

The mission has been modified.

**Pull request merged**
